// ERZEUGT von scripts/generate-mana-symbols.js - nicht von Hand ändern.
//
// Quelle: https://api.scryfall.com/symbology (abgerufen am 2026-09-14),
// gefiltert auf represents_mana === true. Die Bedeutung der Felder steht in mana-symbols.ts,
// die Regelgrundlage in docs/mtg-regeln.md (CR 107.4).

import type { ScryfallManaSymbol } from './mana-symbols';

export const SCRYFALL_MANA_SYMBOLS: readonly ScryfallManaSymbol[] = [
  {
    symbol: '{∞}',
    manaValue: 0,
    colors: [],
    hybrid: false,
    phyrexian: false,
    english: 'infinite generic mana',
  },
  {
    symbol: '{0}',
    manaValue: 0,
    colors: [],
    hybrid: false,
    phyrexian: false,
    english: 'zero mana',
  },
  {
    symbol: '{1}',
    manaValue: 1,
    colors: [],
    hybrid: false,
    phyrexian: false,
    english: 'one generic mana',
  },
  {
    symbol: '{½}',
    manaValue: 0.5,
    colors: [],
    hybrid: false,
    phyrexian: false,
    english: 'one-half generic mana',
  },
  {
    symbol: '{10}',
    manaValue: 10,
    colors: [],
    hybrid: false,
    phyrexian: false,
    english: 'ten generic mana',
  },
  {
    symbol: '{100}',
    manaValue: 100,
    colors: [],
    hybrid: false,
    phyrexian: false,
    english: 'one hundred generic mana',
  },
  {
    symbol: '{1000000}',
    manaValue: 1000000,
    colors: [],
    hybrid: false,
    phyrexian: false,
    english: 'one million generic mana',
  },
  {
    symbol: '{11}',
    manaValue: 11,
    colors: [],
    hybrid: false,
    phyrexian: false,
    english: 'eleven generic mana',
  },
  {
    symbol: '{12}',
    manaValue: 12,
    colors: [],
    hybrid: false,
    phyrexian: false,
    english: 'twelve generic mana',
  },
  {
    symbol: '{13}',
    manaValue: 13,
    colors: [],
    hybrid: false,
    phyrexian: false,
    english: 'thirteen generic mana',
  },
  {
    symbol: '{14}',
    manaValue: 14,
    colors: [],
    hybrid: false,
    phyrexian: false,
    english: 'fourteen generic mana',
  },
  {
    symbol: '{15}',
    manaValue: 15,
    colors: [],
    hybrid: false,
    phyrexian: false,
    english: 'fifteen generic mana',
  },
  {
    symbol: '{16}',
    manaValue: 16,
    colors: [],
    hybrid: false,
    phyrexian: false,
    english: 'sixteen generic mana',
  },
  {
    symbol: '{17}',
    manaValue: 17,
    colors: [],
    hybrid: false,
    phyrexian: false,
    english: 'seventeen generic mana',
  },
  {
    symbol: '{18}',
    manaValue: 18,
    colors: [],
    hybrid: false,
    phyrexian: false,
    english: 'eighteen generic mana',
  },
  {
    symbol: '{19}',
    manaValue: 19,
    colors: [],
    hybrid: false,
    phyrexian: false,
    english: 'nineteen generic mana',
  },
  {
    symbol: '{2}',
    manaValue: 2,
    colors: [],
    hybrid: false,
    phyrexian: false,
    english: 'two generic mana',
  },
  {
    symbol: '{2/B}',
    manaValue: 2,
    colors: ['B'],
    hybrid: true,
    phyrexian: false,
    english: 'two generic mana or one black mana',
  },
  {
    symbol: '{2/G}',
    manaValue: 2,
    colors: ['G'],
    hybrid: true,
    phyrexian: false,
    english: 'two generic mana or one green mana',
  },
  {
    symbol: '{2/R}',
    manaValue: 2,
    colors: ['R'],
    hybrid: true,
    phyrexian: false,
    english: 'two generic mana or one red mana',
  },
  {
    symbol: '{2/U}',
    manaValue: 2,
    colors: ['U'],
    hybrid: true,
    phyrexian: false,
    english: 'two generic mana or one blue mana',
  },
  {
    symbol: '{2/W}',
    manaValue: 2,
    colors: ['W'],
    hybrid: true,
    phyrexian: false,
    english: 'two generic mana or one white mana',
  },
  {
    symbol: '{20}',
    manaValue: 20,
    colors: [],
    hybrid: false,
    phyrexian: false,
    english: 'twenty generic mana',
  },
  {
    symbol: '{3}',
    manaValue: 3,
    colors: [],
    hybrid: false,
    phyrexian: false,
    english: 'three generic mana',
  },
  {
    symbol: '{4}',
    manaValue: 4,
    colors: [],
    hybrid: false,
    phyrexian: false,
    english: 'four generic mana',
  },
  {
    symbol: '{5}',
    manaValue: 5,
    colors: [],
    hybrid: false,
    phyrexian: false,
    english: 'five generic mana',
  },
  {
    symbol: '{6}',
    manaValue: 6,
    colors: [],
    hybrid: false,
    phyrexian: false,
    english: 'six generic mana',
  },
  {
    symbol: '{7}',
    manaValue: 7,
    colors: [],
    hybrid: false,
    phyrexian: false,
    english: 'seven generic mana',
  },
  {
    symbol: '{8}',
    manaValue: 8,
    colors: [],
    hybrid: false,
    phyrexian: false,
    english: 'eight generic mana',
  },
  {
    symbol: '{9}',
    manaValue: 9,
    colors: [],
    hybrid: false,
    phyrexian: false,
    english: 'nine generic mana',
  },
  {
    symbol: '{B}',
    manaValue: 1,
    colors: ['B'],
    hybrid: false,
    phyrexian: false,
    english: 'one black mana',
  },
  {
    symbol: '{B/G}',
    manaValue: 1,
    colors: ['B', 'G'],
    hybrid: true,
    phyrexian: false,
    english: 'one black or green mana',
  },
  {
    symbol: '{B/G/P}',
    manaValue: 1,
    colors: ['B', 'G'],
    hybrid: true,
    phyrexian: true,
    english: 'one black mana, one green mana, or 2 life',
  },
  {
    symbol: '{B/P}',
    manaValue: 1,
    colors: ['B'],
    hybrid: false,
    phyrexian: true,
    english: 'one black mana or two life',
  },
  {
    symbol: '{B/R}',
    manaValue: 1,
    colors: ['B', 'R'],
    hybrid: true,
    phyrexian: false,
    english: 'one black or red mana',
  },
  {
    symbol: '{B/R/P}',
    manaValue: 1,
    colors: ['B', 'R'],
    hybrid: true,
    phyrexian: true,
    english: 'one black mana, one red mana, or 2 life',
  },
  {
    symbol: '{C}',
    manaValue: 1,
    colors: [],
    hybrid: false,
    phyrexian: false,
    english: 'one colorless mana',
  },
  {
    symbol: '{C/B}',
    manaValue: 1,
    colors: ['B'],
    hybrid: true,
    phyrexian: false,
    english: 'one colorless mana or one black mana',
  },
  {
    symbol: '{C/G}',
    manaValue: 1,
    colors: ['G'],
    hybrid: true,
    phyrexian: false,
    english: 'one colorless mana or one green mana',
  },
  {
    symbol: '{C/P}',
    manaValue: 1,
    colors: [],
    hybrid: false,
    phyrexian: true,
    english: 'one colorless mana or two life',
  },
  {
    symbol: '{C/R}',
    manaValue: 1,
    colors: ['R'],
    hybrid: true,
    phyrexian: false,
    english: 'one colorless mana or one red mana',
  },
  {
    symbol: '{C/U}',
    manaValue: 1,
    colors: ['U'],
    hybrid: true,
    phyrexian: false,
    english: 'one colorless mana or one blue mana',
  },
  {
    symbol: '{C/W}',
    manaValue: 1,
    colors: ['W'],
    hybrid: true,
    phyrexian: false,
    english: 'one colorless mana or one white mana',
  },
  {
    symbol: '{G}',
    manaValue: 1,
    colors: ['G'],
    hybrid: false,
    phyrexian: false,
    english: 'one green mana',
  },
  {
    symbol: '{G/P}',
    manaValue: 1,
    colors: ['G'],
    hybrid: false,
    phyrexian: true,
    english: 'one green mana or two life',
  },
  {
    symbol: '{G/U}',
    manaValue: 1,
    colors: ['U', 'G'],
    hybrid: true,
    phyrexian: false,
    english: 'one green or blue mana',
  },
  {
    symbol: '{G/U/P}',
    manaValue: 1,
    colors: ['U', 'G'],
    hybrid: true,
    phyrexian: true,
    english: 'one green mana, one blue mana, or 2 life',
  },
  {
    symbol: '{G/W}',
    manaValue: 1,
    colors: ['W', 'G'],
    hybrid: true,
    phyrexian: false,
    english: 'one green or white mana',
  },
  {
    symbol: '{G/W/P}',
    manaValue: 1,
    colors: ['W', 'G'],
    hybrid: true,
    phyrexian: true,
    english: 'one green mana, one white mana, or 2 life',
  },
  {
    symbol: '{H}',
    manaValue: 1,
    colors: [],
    hybrid: false,
    phyrexian: true,
    english: 'one colored mana or two life',
  },
  {
    symbol: '{HR}',
    manaValue: 0.5,
    colors: ['R'],
    hybrid: false,
    phyrexian: false,
    english: 'one-half red mana',
  },
  {
    symbol: '{HW}',
    manaValue: 0.5,
    colors: ['W'],
    hybrid: false,
    phyrexian: false,
    english: 'one-half white mana',
  },
  {
    symbol: '{L}',
    manaValue: 1,
    colors: [],
    hybrid: false,
    phyrexian: false,
    english: 'one mana from a legendary source',
  },
  {
    symbol: '{R}',
    manaValue: 1,
    colors: ['R'],
    hybrid: false,
    phyrexian: false,
    english: 'one red mana',
  },
  {
    symbol: '{R/G}',
    manaValue: 1,
    colors: ['R', 'G'],
    hybrid: true,
    phyrexian: false,
    english: 'one red or green mana',
  },
  {
    symbol: '{R/G/P}',
    manaValue: 1,
    colors: ['R', 'G'],
    hybrid: true,
    phyrexian: true,
    english: 'one red mana, one green mana, or 2 life',
  },
  {
    symbol: '{R/P}',
    manaValue: 1,
    colors: ['R'],
    hybrid: false,
    phyrexian: true,
    english: 'one red mana or two life',
  },
  {
    symbol: '{R/W}',
    manaValue: 1,
    colors: ['W', 'R'],
    hybrid: true,
    phyrexian: false,
    english: 'one red or white mana',
  },
  {
    symbol: '{R/W/P}',
    manaValue: 1,
    colors: ['W', 'R'],
    hybrid: true,
    phyrexian: true,
    english: 'one red mana, one white mana, or 2 life',
  },
  {
    symbol: '{S}',
    manaValue: 1,
    colors: [],
    hybrid: false,
    phyrexian: false,
    english: 'one snow mana',
  },
  {
    symbol: '{U}',
    manaValue: 1,
    colors: ['U'],
    hybrid: false,
    phyrexian: false,
    english: 'one blue mana',
  },
  {
    symbol: '{U/B}',
    manaValue: 1,
    colors: ['U', 'B'],
    hybrid: true,
    phyrexian: false,
    english: 'one blue or black mana',
  },
  {
    symbol: '{U/B/P}',
    manaValue: 1,
    colors: ['U', 'B'],
    hybrid: true,
    phyrexian: true,
    english: 'one blue mana, one black mana, or 2 life',
  },
  {
    symbol: '{U/P}',
    manaValue: 1,
    colors: ['U'],
    hybrid: false,
    phyrexian: true,
    english: 'one blue mana or two life',
  },
  {
    symbol: '{U/R}',
    manaValue: 1,
    colors: ['U', 'R'],
    hybrid: true,
    phyrexian: false,
    english: 'one blue or red mana',
  },
  {
    symbol: '{U/R/P}',
    manaValue: 1,
    colors: ['U', 'R'],
    hybrid: true,
    phyrexian: true,
    english: 'one blue mana, one red mana, or 2 life',
  },
  {
    symbol: '{W}',
    manaValue: 1,
    colors: ['W'],
    hybrid: false,
    phyrexian: false,
    english: 'one white mana',
  },
  {
    symbol: '{W/B}',
    manaValue: 1,
    colors: ['W', 'B'],
    hybrid: true,
    phyrexian: false,
    english: 'one white or black mana',
  },
  {
    symbol: '{W/B/P}',
    manaValue: 1,
    colors: ['W', 'B'],
    hybrid: true,
    phyrexian: true,
    english: 'one white mana, one black mana, or 2 life',
  },
  {
    symbol: '{W/P}',
    manaValue: 1,
    colors: ['W'],
    hybrid: false,
    phyrexian: true,
    english: 'one white mana or two life',
  },
  {
    symbol: '{W/U}',
    manaValue: 1,
    colors: ['W', 'U'],
    hybrid: true,
    phyrexian: false,
    english: 'one white or blue mana',
  },
  {
    symbol: '{W/U/P}',
    manaValue: 1,
    colors: ['W', 'U'],
    hybrid: true,
    phyrexian: true,
    english: 'one white mana, one blue mana, or 2 life',
  },
  {
    symbol: '{X}',
    manaValue: 0,
    colors: [],
    hybrid: false,
    phyrexian: false,
    english: 'X generic mana',
  },
  {
    symbol: '{Y}',
    manaValue: 0,
    colors: [],
    hybrid: false,
    phyrexian: false,
    english: 'Y generic mana',
  },
  {
    symbol: '{Z}',
    manaValue: 0,
    colors: [],
    hybrid: false,
    phyrexian: false,
    english: 'Z generic mana',
  },
];
